In [1]:
import torch

In [28]:
a = torch.randint(10, (1, 100), dtype=torch.long)[0]
b = torch.randint(10, (1, 50), dtype=torch.long)[0]

In [29]:
a

tensor([8, 8, 0, 8, 7, 0, 2, 0, 4, 3, 0, 1, 1, 4, 4, 3, 0, 6, 0, 0, 7, 5, 8, 7,
        2, 3, 9, 6, 6, 2, 2, 7, 0, 4, 8, 3, 9, 1, 8, 3, 0, 6, 4, 8, 1, 3, 1, 7,
        7, 1, 6, 7, 4, 7, 9, 6, 4, 2, 9, 8, 8, 9, 0, 0, 3, 4, 8, 7, 7, 9, 6, 6,
        5, 1, 5, 4, 7, 2, 1, 4, 3, 5, 0, 2, 6, 3, 3, 6, 8, 5, 3, 5, 3, 8, 2, 7,
        3, 9, 3, 0])

In [30]:
a[0:50].copy_(b)

tensor([6, 2, 6, 2, 1, 4, 1, 2, 1, 9, 1, 1, 9, 0, 1, 4, 1, 4, 1, 7, 2, 7, 6, 3,
        9, 8, 2, 7, 9, 3, 7, 5, 1, 1, 3, 5, 8, 4, 9, 7, 8, 8, 9, 9, 7, 9, 2, 0,
        4, 3])

In [31]:
a

tensor([6, 2, 6, 2, 1, 4, 1, 2, 1, 9, 1, 1, 9, 0, 1, 4, 1, 4, 1, 7, 2, 7, 6, 3,
        9, 8, 2, 7, 9, 3, 7, 5, 1, 1, 3, 5, 8, 4, 9, 7, 8, 8, 9, 9, 7, 9, 2, 0,
        4, 3, 6, 7, 4, 7, 9, 6, 4, 2, 9, 8, 8, 9, 0, 0, 3, 4, 8, 7, 7, 9, 6, 6,
        5, 1, 5, 4, 7, 2, 1, 4, 3, 5, 0, 2, 6, 3, 3, 6, 8, 5, 3, 5, 3, 8, 2, 7,
        3, 9, 3, 0])

In [27]:
b

tensor([2, 1, 9, 9, 4, 4, 4, 1, 7, 1, 8, 5, 3, 9, 9, 9, 2, 5, 3, 3, 4, 9, 2, 1,
        6, 0, 5, 8, 0, 2, 3, 2, 7, 6, 4, 2, 1, 9, 1, 8, 1, 6, 4, 2, 6, 9, 5, 8,
        9, 1])

In [32]:
a = [0]*10
a

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [35]:
a[1:4] = [2]*4
a

[0, 2, 2, 2, 2, 0, 0, 0, 0, 0]

In [36]:
len(None)

TypeError: object of type 'NoneType' has no len()